# Configuration Railway pour Culture Radar

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT"

# Cron jobs pour Railway
[[cron]]
name = "Scraping quotidien"
schedule = "0 6 * * *"  # 6h00 chaque jour
command = "php cron/scrape-events.php"

[[cron]]
name = "Nettoyage hebdomadaire"
schedule = "0 3 * * 0"  # 3h00 chaque dimanche
command = "php cron/cleanup.php"

[[cron]]
name = "Rapport quotidien"
schedule = "0 9 * * *"  # 9h00 chaque jour
command = "php cron/daily-report.php"